[package]
name = "introduction-to-algorithms"
version = "0.1.0"
authors = ["EFanZh <efanzh@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "*"
num-integer = "*"
num-traits = "*"
permutohedron = "*"
rand = "*"
